arch/x86: add missing include to sparsemem.h
Somehow all existing inclusions of sparsemem.h are preceded by inclusion
of <linux/types.h>, but KMSAN contains code that transitively includes
sparsemem.h without that header, resulting in a compilation error:

  sparsemem.h:34:32: error: unknown type name 'phys_addr_t'
  extern int phys_to_target_node(phys_addr_t start);
                                 ^
  sparsemem.h:36:39: error: unknown type name 'u64'
  extern int memory_add_physaddr_to_nid(u64 start);
                                        ^

Because sparsemem.h does actually use phys_addr_t and u64, include
types.h explicitly.

Signed-off-by: Dmitry Vyukov <dvyukov@google.com>
---
Link: https://linux-review.googlesource.com/id/Ifae221ce85d870d8f8d17173bd44d5cf9be2950f