arch/x86: add missing include to sparsemem.h
sparsemem.h:34:32: error: unknown type name 'phys_addr_t'
extern int phys_to_target_node(phys_addr_t start);
                               ^
sparsemem.h:36:39: error: unknown type name 'u64'
extern int memory_add_physaddr_to_nid(u64 start);
                                      ^

Signed-off-by: Dmitry Vyukov <dvyukov@google.com>
Change-Id: I7011b076dff568fbdaed76ce601413c38a9d42bb